spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: from google drive
            client-secret: from google drive
          github:
            client-id: ofujasldkfjalsf
            client-secret: aldsjflaksdjfkl
          facebook:
            client-id: asldfjlaksfjlkasjfd
            client-secret: asldfjalskdfkjalk
